---
- name: SQLmap | Install SQLmap
  apt:
    name:
      - sqlmap
    update_cache: yes
    state: present

- name: MSF | Download script msfinstall
  get_url:
    url: "{{ metasploit_installer_url }}"
    dest: '/tmp/msfinstall'
    mode: '775'

- name: MSF | Check metasploit as installed
  command: msfconsole -v > /dev/null 2>&1
  register: metasploit_installed
  ignore_errors: yes

- name: MSF | Install Metasploit Framework
  command: '/tmp/msfinstall'
  when: metasploit_installed.rc != 0
